wall_follower:
  ros__parameters:
    # topics
    lidarscan_topic: '/scanner/scan'
    drive_topic: '/drive'

    frame_id: 'base_link'

    # PID gains for steering
    kP: 0.5
    kI: 0.0
    kD: 0.0

    # Generally, the front angle of 
    # your car relative to your lidar
    laserscan_phase_deg: 0.0

    # sampling time (sec)
    Ts: 0.02

# won't use here by defalt, 
# you may copy this file to any directory
# just make sure you change "sensor_pkg" to {your_dir} in launch file